SET NAMES UTF8;
DROP DATABASE IF EXISTS multer;
CREATE DATABASE multer CHARSET=UTF8;
USE multer;
CREATE TABLE images(
    id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    imageurl VARCHAR(60) NOT NULL
)